wireguard_interface_name: wg0
wireguard_connection_name: con-{{ wireguard_interface_name }}
wireguard_keystore_directory: "./wireguard_keys"
wireguard_zone: public
wireguard_ipv4_forwarding_needed: true
wireguard_ipv6_forwarding_needed: true
wireguard_port: 51820
wireguard_ipv4subnet: "10.0.0.0/24"
wireguard_ipv6subnet: "fd00:7::/64"
wireguard_clients: []
wireguard_post_up_commands: []
wireguard_post_down_commands: []
wireguard_update_keys: false
