$ANSIBLE_VAULT;1.1;AES256
65353930356162616563323865353031613932366261356436343561383266396465636533663465
6138353661666637666263393864373865616266613830630a363135636636636163623136383738
33646338646233643535366430613866313966346237386339386163316438633539376538386139
3438303031383935630a373863633937393933646162663334633262626236363933383130666133
62646536316436656265616165336235663664386232613132636663366165333835313438323537
62663830663634303563323465633463633739623466653264396136393466333065623062363131
62613336363831353932646464373465613435363339326661643639643532353865653164616139
61383438333063613464616636396561353834373638666337323436626162616438343334663462
31373034666366316666636161356362383737323130643266663733326235353566393431653135
64396138616461343162336161333562386161323439666539313130333264663966376339646231
346663363963353733343837363131356438
