wireguard:
  connection_name: private-net
  zone: public
  ipv4subnet: "10.0.0.1/32"
  ipv6subnet: "fd00:7::1/128"
  port: 51820
  clients:
    - name: gtw01
      ipv4subnet: 10.0.0.0/24
      ipv6subnet: fd00:7::/24
      endpoint: 87.106.13.87:51820
