dante_log_output_file: syslog
dante_privileged_user: root
dante_unprivileged_user: proxy
dante_interface_ip: 0.0.0.0
dante_port: 1080
dante_socks_method: username
dante_client_method: none
dante_client_pass_rules:
  - from: "0.0.0.0/0"
    to: "0.0.0.0/0"
    log: "connect error"
dante_socks_pass_rules:
  - from: "0.0.0.0/0"
    to: "0.0.0.0/0"
    log: "connect error"
