---
- name: Install and configure Cri-o and Kubernetes
  block:

    - name: Imposta il nuovo hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.private"

    - name: Imposta l'hostname Pretty
      ansible.builtin.command:
        cmd: "hostnamectl set-hostname --pretty '{{ hostname }}'"
      changed_when: true

    - name: Aggiorna il file /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ hostname }}.private"
        owner: root
        group: root
        mode: '0644'

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - kubernetes-kubeadm
          - kubernetes
          - containernetworking-plugins
          - iproute-tc
          - socat
          - cri-tools >= 1.32.0
          - cri-o >= 1.32.0
        state: present

    - name: Create /etc/modules-load.d/crio.conf file
      ansible.builtin.copy:
        dest: /etc/modules-load.d/crio.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Modprobe br_netfilter
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Copia la configurazione sysctl completa
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
          net.ipv6.conf.all.forwarding        = 1
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start crio and kubectl service
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
        daemon_reload: true
      loop:
        - crio
        - kubelet

    - name: Disabilita la swap immediatamente (runtime)
      ansible.builtin.command: swapoff -a
      # Esegue il comando solo se la swap Ã¨ effettivamente attiva
      when: |
        ansible_facts['memory_mb']['swap'] is defined and
        ansible_facts['memory_mb']['swap']['total'] > 0
      changed_when: true

    - name: Ensure swap is disabled on boot
      ansible.builtin.file:
        path: /etc/systemd/zram-generator.conf
        state: touch
        owner: root
        group: root
        mode: '0644'
      when: |
        ansible_facts['memory_mb']['swap'] is defined and
        ansible_facts['memory_mb']['swap']['total'] > 0

    - name: Rimuove eventuali partizioni swap da /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    - name: Ensure crio drop-in directory exists
      ansible.builtin.file:
        path: /etc/crio/crio.conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Change the cri-o network configurations
      ansible.builtin.copy:
        dest: /etc/crio/crio.conf.d/99-kubernetes-cni.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          [crio.network]
          network_dir = "/etc/cni/net.d/"
          plugin_dirs = [
            "/usr/libexec/cni",
            "/opt/cni/bin"
          ]
          [crio.runtime]
          conmon_cgroup = "pod"
          cgroup_manager = "systemd"
      notify:
        - Restart crio

    - name: Disable firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
